-- DrSmile Team Dashboard: Supabase schema and row-level security.
-- Safe to run more than once in the Supabase SQL Editor.

create table if not exists public.members (
  id text primary key,
  name text not null,
  role text not null default '',
  email text unique,
  active boolean not null default true,
  is_owner boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.menu_permissions (
  member_id text not null references public.members(id) on delete cascade,
  menu text not null check (menu in ('products','promotions','points','pharmacies','payments','faq','calendar','broadcasts')),
  can_view boolean not null default true,
  can_add boolean not null default false,
  can_edit boolean not null default false,
  can_delete boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (member_id, menu)
);

create table if not exists public.records (
  id bigint generated by default as identity primary key,
  section text not null check (section in ('products','promotions','points','pharmacies','payments','faq','calendar','broadcasts')),
  title text not null,
  subtitle text not null default '',
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists records_section_idx on public.records(section);
create index if not exists members_active_email_idx on public.members (lower(email)) where active and email is not null;

create table if not exists public.dashboard_settings (
  key text primary key,
  value jsonb not null
);

create or replace function public.current_member_id()
returns text language sql stable security definer set search_path = public
as $$ select id from public.members where active and lower(email) = lower(auth.jwt() ->> 'email') limit 1 $$;

create or replace function public.is_dashboard_owner()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.members where id = public.current_member_id() and is_owner and active) $$;

create or replace function public.has_menu_permission(menu_name text, action_name text)
returns boolean language sql stable security definer set search_path = public
as $$
  select public.is_dashboard_owner() or exists (
    select 1 from public.menu_permissions p
    where p.member_id = public.current_member_id() and p.menu = menu_name
      and case action_name
        when 'view' then p.can_view
        when 'add' then p.can_add
        when 'edit' then p.can_edit
        when 'delete' then p.can_delete
        else false
      end
  )
$$;

alter table public.members enable row level security;
alter table public.menu_permissions enable row level security;
alter table public.records enable row level security;
alter table public.dashboard_settings enable row level security;

drop policy if exists "members_read_self_or_owner" on public.members;
create policy "members_read_self_or_owner" on public.members for select to authenticated
using (id = public.current_member_id() or public.is_dashboard_owner());
drop policy if exists "members_owner_insert" on public.members;
create policy "members_owner_insert" on public.members for insert to authenticated with check (public.is_dashboard_owner());
drop policy if exists "members_owner_update" on public.members;
create policy "members_owner_update" on public.members for update to authenticated using (public.is_dashboard_owner()) with check (public.is_dashboard_owner());
drop policy if exists "members_owner_delete" on public.members;
create policy "members_owner_delete" on public.members for delete to authenticated using (public.is_dashboard_owner() and not is_owner);

drop policy if exists "permissions_read_self_or_owner" on public.menu_permissions;
create policy "permissions_read_self_or_owner" on public.menu_permissions for select to authenticated
using (member_id = public.current_member_id() or public.is_dashboard_owner());
drop policy if exists "permissions_owner_insert" on public.menu_permissions;
create policy "permissions_owner_insert" on public.menu_permissions for insert to authenticated with check (public.is_dashboard_owner());
drop policy if exists "permissions_owner_update" on public.menu_permissions;
create policy "permissions_owner_update" on public.menu_permissions for update to authenticated using (public.is_dashboard_owner()) with check (public.is_dashboard_owner());
drop policy if exists "permissions_owner_delete" on public.menu_permissions;
create policy "permissions_owner_delete" on public.menu_permissions for delete to authenticated using (public.is_dashboard_owner());

drop policy if exists "records_menu_read" on public.records;
create policy "records_menu_read" on public.records for select to authenticated using (public.has_menu_permission(section, 'view'));
drop policy if exists "records_menu_add" on public.records;
create policy "records_menu_add" on public.records for insert to authenticated with check (public.has_menu_permission(section, 'add'));
drop policy if exists "records_menu_edit" on public.records;
create policy "records_menu_edit" on public.records for update to authenticated using (public.has_menu_permission(section, 'edit')) with check (public.has_menu_permission(section, 'edit'));
drop policy if exists "records_menu_delete" on public.records;
create policy "records_menu_delete" on public.records for delete to authenticated using (public.has_menu_permission(section, 'delete'));

drop policy if exists "settings_products_read" on public.dashboard_settings;
create policy "settings_products_read" on public.dashboard_settings for select to authenticated using (public.has_menu_permission('products', 'view'));
drop policy if exists "settings_products_insert" on public.dashboard_settings;
create policy "settings_products_insert" on public.dashboard_settings for insert to authenticated with check (public.has_menu_permission('products', 'add'));
drop policy if exists "settings_products_update" on public.dashboard_settings;
create policy "settings_products_update" on public.dashboard_settings for update to authenticated using (public.has_menu_permission('products', 'edit')) with check (public.has_menu_permission('products', 'edit'));

insert into public.members (id, name, role, email, active, is_owner)
values ('admin-joslyn', 'Joslyn', 'Main Account', 'joslyn.drsmile@gmail.com', true, true)
on conflict (id) do update set name = excluded.name, role = excluded.role, email = excluded.email, active = true, is_owner = true;

insert into public.menu_permissions (member_id, menu, can_view, can_add, can_edit, can_delete)
select 'admin-joslyn', menu, true, true, true, true
from unnest(array['products','promotions','points','pharmacies','payments','faq','calendar','broadcasts']) as menu
on conflict (member_id, menu) do update set can_view = true, can_add = true, can_edit = true, can_delete = true;

insert into public.dashboard_settings (key, value)
values ('product_categories', '["牙粉","完整美白疗程","漱口水","加购产品","包包"]'::jsonb)
on conflict (key) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('dashboard-images', 'dashboard-images', true, 5242880, array['image/png','image/jpeg','image/webp'])
on conflict (id) do update set public = true, file_size_limit = 5242880, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "dashboard_images_read" on storage.objects;
create policy "dashboard_images_read" on storage.objects for select using (bucket_id = 'dashboard-images');
drop policy if exists "dashboard_images_upload" on storage.objects;
create policy "dashboard_images_upload" on storage.objects for insert to authenticated with check (bucket_id = 'dashboard-images' and public.current_member_id() is not null);
drop policy if exists "dashboard_images_update" on storage.objects;
create policy "dashboard_images_update" on storage.objects for update to authenticated using (bucket_id = 'dashboard-images' and public.current_member_id() is not null);
drop policy if exists "dashboard_images_delete" on storage.objects;
create policy "dashboard_images_delete" on storage.objects for delete to authenticated using (bucket_id = 'dashboard-images' and public.is_dashboard_owner());
